create table if not exists public.users (
  id text primary key,
  role text not null check (role in ('client', 'admin')),
  name text not null,
  company text not null default '',
  email text not null unique,
  phone text not null default '',
  password text not null,
  is_approved boolean not null default true,
  status text not null default 'Approved',
  created_at timestamptz not null default now()
);

create table if not exists public.payment_methods (
  id bigint generated by default as identity primary key,
  code text not null unique,
  name text not null unique,
  description text not null default '',
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

insert into public.payment_methods (code, name, description)
values
  ('ewallet', 'GCash / Maya', 'E-Wallet'),
  ('card', 'Credit / Debit Card', 'Visa / Mastercard'),
  ('bank_transfer', 'Bank Transfer / Direct Deposit', 'BDO / BPI / Direct Deposit'),
  ('invoice', 'Cash on Delivery / Corporate Invoice', 'COD / Corporate Billing')
on conflict (code) do update set
  name = excluded.name,
  description = excluded.description;

create table if not exists public.bookings (
  id text primary key,
  user_id text references public.users(id) on update cascade on delete set null,
  name text not null,
  email text not null,
  phone text not null default '',
  service_date date,
  subsidiaries jsonb not null default '[]'::jsonb,
  services jsonb not null default '{}'::jsonb,
  notes text not null default '',
  payment_method text not null,
  payment_method_id bigint references public.payment_methods(id) on update cascade on delete restrict,
  status text not null default 'Pending' check (status in ('Pending', 'Approved', 'Rejected')),
  created_at timestamptz not null default now(),
  timestamp timestamptz not null default now(),
  updated_at timestamptz
);

alter table public.bookings add column if not exists user_id text references public.users(id) on update cascade on delete set null;
alter table public.bookings add column if not exists payment_method_id bigint references public.payment_methods(id) on update cascade on delete restrict;

update public.bookings as b
set user_id = u.id
from public.users as u
where b.user_id is null and lower(b.email) = lower(u.email);

update public.bookings as b
set payment_method_id = p.id
from public.payment_methods as p
where b.payment_method_id is null and b.payment_method = p.name;

create index if not exists bookings_email_idx on public.bookings (email);
create index if not exists bookings_user_id_idx on public.bookings (user_id);
create index if not exists bookings_payment_method_id_idx on public.bookings (payment_method_id);
create index if not exists bookings_status_idx on public.bookings (status);
create index if not exists users_role_status_idx on public.users (role, status);

alter table public.users enable row level security;
alter table public.payment_methods enable row level security;
alter table public.bookings enable row level security;
