create table if not exists public.users (
  id text primary key,
  role text not null check (role in ('client', 'admin')),
  name text not null,
  company text not null default '',
  email text not null unique,
  phone text not null default '',
  password text not null,
  is_approved boolean not null default true,
  status text not null default 'Approved',
  created_at timestamptz not null default now()
);

-- Supabase Auth profiles for client accounts created by auth.signUp().
-- The profile ID is the Auth user's UUID, not the legacy public.users text ID.
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  name text not null default '',
  email text,
  phone text not null default '',
  company text not null default '',
  role text not null default 'client' check (role in ('client', 'admin')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Backfill columns for an existing profiles table without changing existing data.
alter table public.profiles
  add column if not exists id uuid references auth.users(id) on delete cascade,
  add column if not exists name text not null default '',
  add column if not exists email text,
  add column if not exists phone text not null default '',
  add column if not exists company text not null default '',
  add column if not exists role text not null default 'client',
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now();

-- The trigger's ON CONFLICT target must be unique even if the table pre-existed.
create unique index if not exists profiles_id_uidx on public.profiles (id);

alter table public.profiles enable row level security;
grant select, insert on public.profiles to authenticated;
grant all on public.profiles to service_role;

drop policy if exists "Users can read their own profile" on public.profiles;
create policy "Users can read their own profile"
  on public.profiles
  for select
  to authenticated
  using ((select auth.uid()) = id);

drop policy if exists "Users can create their own profile" on public.profiles;
create policy "Users can create their own profile"
  on public.profiles
  for insert
  to authenticated
  with check ((select auth.uid()) = id);

-- Recreate the Auth signup trigger with fields matching the client signup metadata.
drop trigger if exists on_auth_user_created on auth.users;
drop function if exists public.handle_new_user();

create function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  profile_name text;
begin
  profile_name := coalesce(
    nullif(pg_catalog.btrim(new.raw_user_meta_data ->> 'full_name'), ''),
    nullif(pg_catalog.btrim(new.raw_user_meta_data ->> 'name'), ''),
    nullif(pg_catalog.split_part(coalesce(new.email, ''), '@', 1), ''),
    'Client'
  );

  insert into public.profiles (
    id,
    name,
    email,
    phone,
    company,
    role,
    created_at,
    updated_at
  )
  values (
    new.id,
    profile_name,
    new.email,
    coalesce(
      nullif(pg_catalog.btrim(new.raw_user_meta_data ->> 'phone'), ''),
      new.phone,
      ''
    ),
    coalesce(nullif(pg_catalog.btrim(new.raw_user_meta_data ->> 'company'), ''), ''),
    'client',
    coalesce(new.created_at, pg_catalog.now()),
    pg_catalog.now()
  )
  on conflict (id) do update
  set
    name = excluded.name,
    email = excluded.email,
    phone = excluded.phone,
    company = excluded.company,
    updated_at = pg_catalog.now();

  return new;
end;
$$;

revoke all on function public.handle_new_user() from public, anon, authenticated;

create trigger on_auth_user_created
  after insert on auth.users
  for each row
  execute function public.handle_new_user();

create table if not exists public.payment_methods (
  id bigint generated by default as identity primary key,
  code text not null unique,
  name text not null unique,
  description text not null default '',
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

insert into public.payment_methods (code, name, description)
values
  ('ewallet', 'GCash / Maya', 'E-Wallet'),
  ('card', 'Credit / Debit Card', 'Visa / Mastercard'),
  ('bank_transfer', 'Bank Transfer / Direct Deposit', 'BDO / BPI / Direct Deposit'),
  ('invoice', 'Cash on Delivery / Corporate Invoice', 'COD / Corporate Billing')
on conflict (code) do update set
  name = excluded.name,
  description = excluded.description;

create table if not exists public.bookings (
  id text primary key,
  user_id text references public.users(id) on update cascade on delete set null,
  name text not null,
  email text not null,
  phone text not null default '',
  service_date date,
  subsidiaries jsonb not null default '[]'::jsonb,
  services jsonb not null default '{}'::jsonb,
  notes text not null default '',
  payment_method text not null,
  payment_method_id bigint references public.payment_methods(id) on update cascade on delete restrict,
  status text not null default 'Pending' check (status in ('Pending', 'Approved', 'Rejected')),
  created_at timestamptz not null default now(),
  timestamp timestamptz not null default now(),
  updated_at timestamptz
);

alter table public.bookings add column if not exists user_id text references public.users(id) on update cascade on delete set null;
alter table public.bookings add column if not exists payment_method_id bigint references public.payment_methods(id) on update cascade on delete restrict;

update public.bookings as b
set user_id = u.id
from public.users as u
where b.user_id is null and lower(b.email) = lower(u.email);

update public.bookings as b
set payment_method_id = p.id
from public.payment_methods as p
where b.payment_method_id is null and b.payment_method = p.name;

create index if not exists bookings_email_idx on public.bookings (email);
create index if not exists bookings_user_id_idx on public.bookings (user_id);
create index if not exists bookings_payment_method_id_idx on public.bookings (payment_method_id);
create index if not exists bookings_status_idx on public.bookings (status);
create index if not exists users_role_status_idx on public.users (role, status);

alter table public.users enable row level security;
alter table public.payment_methods enable row level security;
alter table public.bookings enable row level security;
